Repository KULeuvenNeuromechanics/PredSim, pull requests merged in 2023-04, with the labels that each got.

#80 New heelstrike detection
  OCP/OCP_formulation.m
  OCP/getHeelstrikeSimulation.m
  OCP/getStancePhaseSimulation.m
  PlotFigures/run_this_file_to_plot_figures.m
  Tests/test_getStancePhaseSimulation.m
  main.m
  run_pred_sim.m
Labels: enhancement, bugfix

#86 Add pelvis ty warning
  DefaultSettings/getDefaultSettings.m
  DefaultSettings/initializeSettings.m
  README.md
  main.m
Labels: documentation, enhancement

#90 Create LICENSE
  LICENSE
Labels: documentation
