Repository KULeuvenNeuromechanics/PredSim, pull requests merged in 2024-08, with the labels that each got.

#130 Update coord limit torques
  CasadiFunctions/createCasadi_PassiveMoments.m
  DefaultSettings/getDefaultSettings.m
  PreProcessing/default_coord_lim_torq_coeff.csv
  PreProcessing/get_default_coord_limit_torque_coefficients.m
  PreProcessing/get_passive_moment_info.m
  README.md
Labels: enhancement, Review: moderate

#145 Update getStancePhaseSimulation.m
  OCP/getStancePhaseSimulation.m
Labels: bugfix, Review: easy

#143 Add example 2D model
  .gitignore
  Subjects/gait1018/gait1018.osim
  Subjects/gait1018/readme.md
  Subjects/gait1018/settings_gait1018.m
Labels: enhancement, Review: easy

#133 identify_kinematic_chains-with-branches
  PreProcessing/identify_kinematic_chains.m
Labels: enhancement, Review: moderate

#138 Update PrivateForkPredSim.md for better history keeping
  PrivateForkPredSim.md
Labels: documentation, Review: easy

#151 Bugfix example models
  Subjects/DHondt_2023_2seg/DHondt_2023_2seg.osim
  Subjects/DHondt_2023_2seg/readme.md
  Subjects/DHondt_2023_2seg/settings_DHondt_2023_2seg.m
  Subjects/DHondt_2023_3seg/DHondt_2023_3seg.osim
  Subjects/DHondt_2023_3seg/readme.md
  Subjects/DHondt_2023_3seg/settings_DHondt_2023_3seg.m
  Subjects/DHondt_et_al_2024_3seg/settings_DHondt_et_al_2024_3seg.m
Labels: bugfix, Review: easy

#147 Documentation for results
  Documentation/Hill-type muscle model.svg
  Documentation/ResultsStructure.md
  PostProcessing/PostProcess_spatio_temporal.m
Labels: documentation, Review: easy
