Repository KULeuvenNeuromechanics/PredSim, pull requests merged in 2024-06, with the labels that each got.

#128 Bugfix reference results
  PlotFigures/run_this_file_to_plot_figures.m
Labels: bugfix, Review: easy

#126 Add muscle strength scale in energetics of Bhargava model
  CasadiFunctions/createCasadi_E_Metab.m
  CasadiFunctions/getMetabolicEnergySmooth2004all.m
Labels: bugfix

#131 Save info about polynomial fit of musculoskeletal geometry
  PreProcessing/get_musculoskeletal_geometry_approximation.m
Labels: enhancement, Review: easy
