Repository KULeuvenNeuromechanics/PredSim, pull requests merged in 2024-01, with the labels that each got.

#91 Add implementation ligaments
  .gitignore
  CasadiFunctions/createCasadiFunctions.m
  CasadiFunctions/createCasadi_Ligaments.m
  Debug/polynomials.md
  DefaultSettings/getDefaultSettings.m
  DefaultSettings/initializeSettings.m
  ModelComponents/ligamentForceLength_template.m
  ModelComponents/ligamentGefen2002.m
  ModelComponents/plantarFasciaGefen2002.m
  ModelComponents/plantarFasciaNatali2010.m
  OCP/OCP_formulation.m
  OCP/getBounds.m
  PlotFigures/plot_figures.m
  PlotFigures/run_this_file_to_plot_figures.m
  PostProcessing/PostProcessing.m
  PostProcessing/PostProcessing_ligaments.m
  PreProcessing/PolynomialFit.m
  PreProcessing/PreProcessing.m
  PreProcessing/get_default_coord_limit_torque_coefficients.m
  PreProcessing/get_ligament_info.m
  PreProcessing/get_model_info.m
  PreProcessing/get_muscle_spanning_joint_info.m
  PreProcessing/get_musculoskeletal_geometry_approximation.m
  PreProcessing/muscleAnalysisAPI.m
  README.md
  Subjects/DHondt_2023_2seg/DHondt_2023_2seg.osim
  Subjects/DHondt_2023_2seg/readme.md
  Subjects/DHondt_2023_2seg/settings_DHondt_2023_2seg.m
  Subjects/DHondt_2023_3seg/DHondt_2023_3seg.osim
  Subjects/DHondt_2023_3seg/readme.md
  Subjects/DHondt_2023_3seg/settings_DHondt_2023_3seg.m
  Subjects/Falisse_et_al_2022/settings_Falisse_et_al_2022.m
  Subjects/Hamner_modified/ReadMe.md
  Subjects/README.md
  Tests/test_unpack_name_value_combinations.m
  VariousFunctions/double_array_to_struct_array.m
  VariousFunctions/smoothIf.m
  VariousFunctions/unpack_name_value_combinations.m
  main.m
  run_pred_sim.m
Labels: enhancement, Review: advanced (OpenSim), Review: advanced (CasADi)

#115 Update run_pred_sim.m
  run_pred_sim.m
Labels: bugfix

#110 add computername to settings struct
  DefaultSettings/initializeSettings.m
  README.md
Labels: enhancement

#92 Robust symmetry and limb detection
  DefaultSettings/getDefaultSettings.m
  OCP/OCP_formulation.m
  OCP/getBounds.m
  OCP/getGuess_DI_opti.m
  OCP/getGuess_QR_opti.m
  PreProcessing/get_model_info.m
  PreProcessing/identify_kinematic_chains.m
  PreProcessing/update_model_info.m
  README.md
  Tests/test_identify_kinematic_chain.m
  VariousFunctions/mirrorName.m
Labels: enhancement, about hard coded stuff, Review: advanced (OpenSim)

#82 Create scaleContactSpheres.m
  AdaptOpenSimModel/AdaptOpenSimModel.m
  AdaptOpenSimModel/scaleContactSpheres.m
  README.md
Labels: enhancement, Review: advanced (OpenSim)
