Repository KULeuvenNeuromechanics/PredSim, pull requests merged in 2024-09, with the labels that each got.

#153 Readme update
  .gitignore
  Documentation/FiguresForDocumentation/Hill-type muscle model.svg
  Documentation/FiguresForDocumentation/PredSim logo.png
  Documentation/FiguresForDocumentation/fig_MSVS.png
  Documentation/FiguresForDocumentation/fig_muscle_tendon_properties_scaling.png
  Documentation/FiguresForDocumentation/muscle_tendon_properties_scaling.m
  Documentation/PrivateForkPredSim.md
  Documentation/SettingsOverview.md
  README.md
Labels: documentation

#156 bugfix-get_git_hash
  DefaultSettings/get_git_hash.m
  DefaultSettings/initializeSettings.m
Labels: bugfix

#155 Setting batch job paths
  DefaultSettings/getDefaultSettings.m
  DefaultSettings/initializeSettings.m
  Documentation/SettingsOverview.md
  add_pred_sim_to_batch.m
Labels: documentation, bugfix

#158 Implementing synergies
  CasadiFunctions/createCasadiFunctions.m
  CasadiFunctions/createCasadi_TrackSynW.m
  DefaultSettings/getDefaultSettings.m
  Documentation/SettingsOverview.md
  Examples/synergies.m
  OCP/OCP_formulation.m
  OCP/getBounds.m
  OCP/getGuess_DI_opti.m
  OCP/getGuess_QR_opti.m
  PreProcessing/get_model_info.m
Labels: enhancement, Review: advanced (CasADi)

#159 Update README.md
  README.md
Labels: documentation

#160 Add example scripts
  .gitignore
  Examples/ankle_exoskeleton.m
  Examples/batch_sensitivity_analysis.m
  README.md
  WearableDevices/ankleExoZhang2017.m
Labels: Review: easy

#166 Add scaling of ligaments
  AdaptOpenSimModel/AdaptOpenSimModel.m
  AdaptOpenSimModel/scaleLigaments.m
Labels: enhancement, Review: easy

#169 Update README.md - link guidelines for contributing
  README.md
Labels: documentation, Review: easy

#171 bugfix missing frame mot file
  OCP/OCP_formulation.m
  PostProcessing/PostProcess_spatio_temporal.m
  PostProcessing/PostProcess_write_motion_file.m
Labels: bugfix

#168 Bugfix identify kinematic chains
  PreProcessing/identify_kinematic_chains.m
Labels: bugfix, Review: easy

#161 Documentation model
  Documentation/ModelPreparation.md
  ModelComponents/ligamentForceLength_template.m
  ModelComponents/ligamentGefen2002.m
  README.md
Labels: documentation, help wanted, Review: easy
